project_id = "tpakzgbamrkrnctvgomg"

[functions.sync-spotify-likes]
verify_jwt = false

[functions.tidal-auth-url]
verify_jwt = false

[functions.tidal-exchange-token]
verify_jwt = false

[functions.sync-tidal-likes]
verify_jwt = false