ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS sync_spotify BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS sync_youtube BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS sync_tidal BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS sync_apple_music BOOLEAN NOT NULL DEFAULT TRUE;
